spring:
  profiles:
    active: prod
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: admin
#  jpa:
#    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: localhost #Redis服务器地址
#    port: 6379 #Redis服务器连接端口
#    pool:
#      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 8 #连接池最大空闲连接
#      min-idle: 0 #连接池最小空闲连接
#    timeout: 0 #连接超时时间 （毫秒）
#
#server:
#  context-path: /sell
#  port: 8080
#project:
#  url: 111abc